# Generated by Django 5.0.2 on 2024-02-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproperty',
            name='renter_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
